// 100 句金句 + 表情情绪配对。按当日日期 hash 决定，所有用户同日看到同一对。
// 改/加/换：直接编辑 QUOTES 数组的 mood 字段或 text/source。

export const STICKERS = {
  morning:   '/stickers/Morning.png',
  whatt:     '/stickers/Whatt.png',
  huh:       '/stickers/Huh.png',
  reminding: '/stickers/reminding.png',
  sleepy:    '/stickers/sleepy.png',
  wow:       '/stickers/wow.png',
  approved:  '/stickers/approved.png',
  nice:      '/stickers/Nice.png',
  love:      '/stickers/love.png',
  heyyou:    '/stickers/hey%20you.png',
  achoo:     '/stickers/Achoo.png',
  angry:     '/stickers/angry.png',
  questions: '/stickers/questions.png',
  goodnight: '/stickers/Good%20Night.png',
  cute:      '/stickers/cuteee.png',
  cool:      '/stickers/cool.png',
};

export const QUOTES = [
  { text: '学而时习之，不亦说乎。', source: '《论语·学而》', mood: 'morning' },
  { text: '三人行，必有我师焉。', source: '《论语·述而》', mood: 'heyyou' },
  { text: '知之者不如好之者，好之者不如乐之者。', source: '《论语·雍也》', mood: 'wow' },
  { text: '君子务本，本立而道生。', source: '《论语·学而》', mood: 'approved' },
  { text: '工欲善其事，必先利其器。', source: '《论语·卫灵公》', mood: 'reminding' },
  { text: '不患人之不己知，患不知人也。', source: '《论语·学而》', mood: 'huh' },
  { text: '君子坦荡荡，小人长戚戚。', source: '《论语·述而》', mood: 'cool' },
  { text: '见贤思齐焉，见不贤而内自省也。', source: '《论语·里仁》', mood: 'nice' },
  { text: '己所不欲，勿施于人。', source: '《论语·颜渊》', mood: 'cute' },
  { text: '学而不思则罔，思而不学则殆。', source: '《论语·为政》', mood: 'questions' },
  { text: '君子和而不同，小人同而不和。', source: '《论语·子路》', mood: 'cool' },
  { text: '岁寒，然后知松柏之后凋也。', source: '《论语·子罕》', mood: 'cool' },
  { text: '知者不惑，仁者不忧，勇者不惧。', source: '《论语·子罕》', mood: 'cool' },
  { text: '言必信，行必果。', source: '《论语·子路》', mood: 'nice' },
  { text: '不愤不启，不悱不发。', source: '《论语·述而》', mood: 'reminding' },
  { text: '君子欲讷于言而敏于行。', source: '《论语·里仁》', mood: 'huh' },
  { text: '朝闻道，夕死可矣。', source: '《论语·里仁》', mood: 'wow' },
  { text: '三军可夺帅也，匹夫不可夺志也。', source: '《论语·子罕》', mood: 'angry' },
  { text: '人无远虑，必有近忧。', source: '《论语·卫灵公》', mood: 'reminding' },
  { text: '天将降大任于斯人也，必先苦其心志。', source: '《孟子·告子下》', mood: 'angry' },
  { text: '富贵不能淫，贫贱不能移，威武不能屈。', source: '《孟子·滕文公下》', mood: 'angry' },
  { text: '老吾老以及人之老，幼吾幼以及人之幼。', source: '《孟子·梁惠王上》', mood: 'love' },
  { text: '得道者多助，失道者寡助。', source: '《孟子·公孙丑下》', mood: 'nice' },
  { text: '生于忧患，死于安乐。', source: '《孟子·告子下》', mood: 'reminding' },
  { text: '尽信书，则不如无书。', source: '《孟子·尽心下》', mood: 'whatt' },
  { text: '穷则独善其身，达则兼善天下。', source: '《孟子·尽心上》', mood: 'cool' },
  { text: '仁者爱人，有礼者敬人。', source: '《孟子·离娄下》', mood: 'love' },
  { text: '大学之道，在明明德，在亲民，在止于至善。', source: '《大学》', mood: 'morning' },
  { text: '苟日新，日日新，又日新。', source: '《大学》', mood: 'approved' },
  { text: '修身、齐家、治国、平天下。', source: '《大学》', mood: 'wow' },
  { text: '知止而后有定，定而后能静。', source: '《大学》', mood: 'goodnight' },
  { text: '凡事豫则立，不豫则废。', source: '《中庸》', mood: 'reminding' },
  { text: '博学之，审问之，慎思之，明辨之，笃行之。', source: '《中庸》', mood: 'questions' },
  { text: '君子素其位而行，不愿乎其外。', source: '《中庸》', mood: 'cool' },
  { text: '志不立，天下无可成之事。', source: '王阳明《教条示龙场诸生》', mood: 'angry' },
  { text: '知行合一。', source: '王阳明《传习录》', mood: 'approved' },
  { text: '知是行的主意，行是知的功夫。', source: '王阳明《传习录》', mood: 'questions' },
  { text: '心即理也。', source: '王阳明《传习录》', mood: 'huh' },
  { text: '此心不动，随机而动。', source: '王阳明', mood: 'cool' },
  { text: '破山中贼易，破心中贼难。', source: '王阳明《与杨仕德薛尚谦书》', mood: 'angry' },
  { text: '人须在事上磨，方立得住。', source: '王阳明《传习录》', mood: 'reminding' },
  { text: '圣人之道，吾性自足。', source: '王阳明《传习录》', mood: 'wow' },
  { text: '致良知。', source: '王阳明《传习录》', mood: 'approved' },
  { text: '千圣皆过影，良知乃吾师。', source: '王阳明《咏良知》', mood: 'cool' },
  { text: '千里之行，始于足下。', source: '《道德经》', mood: 'morning' },
  { text: '上善若水。', source: '《道德经》', mood: 'goodnight' },
  { text: '知人者智，自知者明。', source: '《道德经》', mood: 'huh' },
  { text: '胜人者有力，自胜者强。', source: '《道德经》', mood: 'angry' },
  { text: '大方无隅，大器晚成。', source: '《道德经》', mood: 'sleepy' },
  { text: '合抱之木，生于毫末。', source: '《道德经》', mood: 'reminding' },
  { text: '天下难事，必作于易。', source: '《道德经》', mood: 'reminding' },
  { text: '为学日益，为道日损。', source: '《道德经》', mood: 'questions' },
  { text: '吾生也有涯，而知也无涯。', source: '《庄子·养生主》', mood: 'sleepy' },
  { text: '天地与我并生，万物与我为一。', source: '《庄子·齐物论》', mood: 'wow' },
  { text: '君子之交淡如水。', source: '《庄子·山木》', mood: 'cute' },
  { text: '天行健，君子以自强不息。', source: '《周易·乾卦》', mood: 'angry' },
  { text: '地势坤，君子以厚德载物。', source: '《周易·坤卦》', mood: 'cute' },
  { text: '穷则变，变则通，通则久。', source: '《周易·系辞下》', mood: 'whatt' },
  { text: '善不积不足以成名。', source: '《周易·系辞下》', mood: 'reminding' },
  { text: '如切如磋，如琢如磨。', source: '《诗经·卫风·淇奥》', mood: 'nice' },
  { text: '靡不有初，鲜克有终。', source: '《诗经·大雅·荡》', mood: 'reminding' },
  { text: '高山仰止，景行行止。', source: '《诗经·小雅·车舝》', mood: 'wow' },
  { text: '投我以木桃，报之以琼瑶。', source: '《诗经·卫风·木瓜》', mood: 'love' },
  { text: '满招损，谦受益。', source: '《尚书·大禹谟》', mood: 'achoo' },
  { text: '玩人丧德，玩物丧志。', source: '《尚书·旅獒》', mood: 'angry' },
  { text: '民惟邦本，本固邦宁。', source: '《尚书·五子之歌》', mood: 'wow' },
  { text: '玉不琢，不成器；人不学，不知道。', source: '《礼记·学记》', mood: 'approved' },
  { text: '学然后知不足，教然后知困。', source: '《礼记·学记》', mood: 'huh' },
  { text: '独学而无友，则孤陋而寡闻。', source: '《礼记·学记》', mood: 'heyyou' },
  { text: '锲而不舍，金石可镂。', source: '《荀子·劝学》', mood: 'angry' },
  { text: '不积跬步，无以至千里。', source: '《荀子·劝学》', mood: 'reminding' },
  { text: '青，取之于蓝，而青于蓝。', source: '《荀子·劝学》', mood: 'wow' },
  { text: '学不可以已。', source: '《荀子·劝学》', mood: 'reminding' },
  { text: '路漫漫其修远兮，吾将上下而求索。', source: '屈原《离骚》', mood: 'cool' },
  { text: '长风破浪会有时，直挂云帆济沧海。', source: '李白《行路难》', mood: 'wow' },
  { text: '会当凌绝顶，一览众山小。', source: '杜甫《望岳》', mood: 'wow' },
  { text: '读书破万卷，下笔如有神。', source: '杜甫《奉赠韦左丞丈》', mood: 'approved' },
  { text: '黑发不知勤学早，白首方悔读书迟。', source: '颜真卿《劝学》', mood: 'angry' },
  { text: '业精于勤，荒于嬉。', source: '韩愈《进学解》', mood: 'reminding' },
  { text: '古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。', source: '苏轼《晁错论》', mood: 'angry' },
  { text: '纸上得来终觉浅，绝知此事要躬行。', source: '陆游《冬夜读书示子聿》', mood: 'questions' },
  { text: '问渠那得清如许，为有源头活水来。', source: '朱熹《观书有感》', mood: 'questions' },
  { text: '莫等闲，白了少年头，空悲切。', source: '岳飞《满江红》', mood: 'angry' },
  { text: '先天下之忧而忧，后天下之乐而乐。', source: '范仲淹《岳阳楼记》', mood: 'wow' },
  { text: '海纳百川，有容乃大。', source: '林则徐', mood: 'cool' },
  { text: '苟利国家生死以，岂因祸福避趋之。', source: '林则徐《赴戍登程口占示家人》', mood: 'angry' },
  { text: '燕雀安知鸿鹄之志哉。', source: '《史记·陈涉世家》', mood: 'angry' },
  { text: '失之毫厘，谬以千里。', source: '《史记·太史公自序》', mood: 'whatt' },
  { text: '桃李不言，下自成蹊。', source: '《史记·李将军列传》', mood: 'cute' },
  { text: '一寸光阴一寸金，寸金难买寸光阴。', source: '《增广贤文》', mood: 'reminding' },
  { text: '少壮不努力，老大徒伤悲。', source: '汉乐府《长歌行》', mood: 'angry' },
  { text: '三日不读书，便觉言语无味。', source: '黄庭坚', mood: 'achoo' },
  { text: '不积细流，无以成江海。', source: '《荀子·劝学》', mood: 'reminding' },
  { text: '不怨天，不尤人。', source: '《论语·宪问》', mood: 'cool' },
  { text: '见义不为，无勇也。', source: '《论语·为政》', mood: 'angry' },
  { text: '君子求诸己，小人求诸人。', source: '《论语·卫灵公》', mood: 'huh' },
  { text: '过而不改，是谓过矣。', source: '《论语·卫灵公》', mood: 'angry' },
  { text: '行远必自迩，登高必自卑。', source: '《中庸》', mood: 'reminding' },
  { text: '敏于事而慎于言。', source: '《论语·学而》', mood: 'approved' },
  { text: '千淘万漉虽辛苦，吹尽狂沙始到金。', source: '刘禹锡《浪淘沙》', mood: 'angry' },
];

// Deterministic daily pick — all users see same quote per calendar day.
export function pickDaily(date = new Date()) {
  const key = date.toISOString().slice(0, 10); // YYYY-MM-DD
  let hash = 0;
  for (let i = 0; i < key.length; i++) {
    hash = ((hash << 5) - hash) + key.charCodeAt(i);
    hash |= 0;
  }
  const q = QUOTES[Math.abs(hash) % QUOTES.length];
  return { ...q, sticker: STICKERS[q.mood] };
}
